### ISSUE TITLE
Crash on preset save configuration

### ISSUE THREAD

**Issue by kyouens** [mkchoi212/Warp#1]
Purchased warp today.  Having a bit of trouble.  When I try to save my first preset, the app crashes.  Is there a log file I can send you to troublehsoot? 

----
Hardware Overview:

  Model Name:	MacBook Pro
  Model Identifier:	MacBookPro18,1
  Chip:	Apple M1 Pro
  Total Number of Cores:	10 (8 performance and 2 efficiency)
  Memory:	16 GB
  System Firmware Version:	7459.121.3
  OS Loader Version:	7459.121.3

**Comment by mkchoi212** [comment]
Hey @kyouens, wow thanks for finding me on Github :) I'm sorry for the inconvenience and am working to fix the bug asap! In fact, we just released version 1.0.6. Could go to Preferences (gear icon in top right) -> Check for updates to download the latest release and see if the issue is still reproducible?

Thank you

**Comment by kyouens** [comment]
Updated worked! No more crash 😊. Thanks!

From: Mike JS. Choi ***@***.***>
Date: Thursday, June 23, 2022 at 1:00 PM
To: mkchoi212/Warp ***@***.***>
Cc: Kenneth Youens ***@***.***>, Mention ***@***.***>
Subject: Re: [mkchoi212/Warp] Crash on preset save configuration (Issue #1)

Hey @kyouens<https://github.com/kyouens>, wow thanks for finding me on Github :) I'm sorry for the inconvenience and am working to fix the bug asap! In fact, we just released version 1.0.6. Could go to Preferences (gear icon in top right) -> Check for updates to download the latest release and see if the issue is still reproducible?

Thank you

**Comment by mkchoi212** [comment]
Awesome! Thanks for trying it out so fast 😄 Enjoy Warp and please feel free to reach out to https://twitter.com/WarpMacOS whenever you have a question / suggestion / feedback 👍
